# kfood-kind-config.yaml
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: kfood # 클러스터 이름 (kfood로 설정)
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 30081 
    hostPort: 30081
    listenAddress: "0.0.0.0" # 모든 네트워크 인터페이스에 바인딩