apiVersion: v1
kind: Service
metadata:
  name: faiss-db-service
  labels:
    app: faiss-db
spec:
  selector:
    app: faiss-db
  type: ClusterIP # 내부 통신용
  ports:
    - protocol: TCP
      port: 8002
      targetPort: 8002
