apiVersion: v1
kind: Service
metadata:
  name: translate-service-service
  labels:
    app: translate-service
spec:
  selector:
    app: translate-service
  type: ClusterIP # 내부 통신용
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8001
      