apiVersion: apps/v1
kind: Deployment
metadata:
  name: kfood-frontend-deployment
  labels:
    app: kfood-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kfood-frontend
  template:
    metadata:
      labels:
        app: kfood-frontend
    spec:
      containers:
        - name: kfood-frontend
          image: pes112/kfood-frontend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: RECOMMENDER_INTERNAL_URL
              value: "http://kfood-recommender-service:80"
            - name: NEXT_PUBLIC_RECOMMENDER_URL
              value: "http://localhost:30080"
            - name: HOST 
              value: "0.0.0.0"
            - name: PORT # PORT 환경 변수 추가
              value: "3000"
          livenessProbe:
            httpGet:
              path: /api/health
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /api/health
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5
